### ISSUE TITLE
Possible to generify functions to use MonadIO instead of IO directly?

### ISSUE THREAD

**Issue by bbarker** [singpolyma/unexceptionalio#18]
Prime candidates would include `fromIO` from my initial perspective.

I'm not sure how you would use something like `fromIO` on an `m IO` where we have `MonadIO m`, currently.

**Comment by bbarker** [comment]
Actually, in my particular case, I was able to deal with the issue as I was only calling functions that used `MonadIO m` as a constraint - for me, `m` *was* `IO`, so not a problem.

**Comment by singpolyma** [comment]
You may be interested in unexceptionalio-trans

**Comment by bbarker** [comment]
I was in fact using it, but I'm a bit new to monad transformers and nothing jumped out at me for this particular use case, e.g. something like:  `(MonadIO m, Unexceptional u) => m a -> ExceptT SomeNonPseudoException u a`

**Comment by singpolyma** [comment]
Oh, monadio in argument position isn't possible because the typeclass 
only lets us convert things *into* it, not to unwrap things.

**Comment by bbarker** [comment]
I may be getting a bit off-topic but it seems a little unintuitive to me that, since basically anything can be done in IO, other IO-like things can't be lifted into IO: `m a -> IO a`. There's also [unliftIO](https://hackage.haskell.org/package/unliftio-core-0.2.0.1/docs/Control-Monad-IO-Unlift.html#v:unliftIO), though I've found it confusing for related reasons.

**Comment by singpolyma** [comment]
Yeah, there are several of those. Monad-peel etc. or just use the 
unwrappers for your particular transformer stack. Monsd transformers are 
just convenience APIs around operations being done in the base, as you 
saym so you can always unlift, at least with standard ones.

For unexceptional specifically I would recommend catching with fromio at 
the edges before lifting into a transformer, if at all possible. The 
premise is that we wish UIO were the definition for IO in thr first place

**Comment by bbarker** [comment]
I was just wondering if it is worth considering changing `UIO` to be:

```haskell
newtype UIO m a = UIO (m a)
```

Then have functions like:

```haskell
run :: MonadUnliftIO m => UIO a -> m a
run (UIO io) = io

```

Then you could also (possibly - haven't tested this) use e.g. [RIO](https://github.com/commercialhaskell/rio#monads) with UIO to achieve something similar to ZIO, which is a monad that seems to cover most use cases (and I gather UIO was part of the inspiration for ZIO).

I'm not even convinced this is a good idea with certainty; other approaches, such as redefining RIO to use UIO might be better (but less flexible in some sense). Also worth mentioning is [Trio](https://github.com/snoyberg/trio), however, with the UIO-based approach we'd still be relying on Either (somewhat unlike Trio and ZIO).
