### ISSUE TITLE
Add to stackage?

### ISSUE THREAD

**Issue by bbarker** [singpolyma/unexceptionalio#19]
It might be nice to have UIO available through stackage (for LTS releases): https://github.com/commercialhaskell/stackage

**Comment by bbarker** [comment]
I created a pull request here, but feel free to  make a new PR after it is added to have your name etc added as the maintainer: https://github.com/commercialhaskell/stackage/pull/5411

**Comment by singpolyma** [comment]
I haven't been following stackage much since the original launch -- is the PR you have put in sufficient, and it just means you will be responsible for updating stackage-specific metadata, etc going forward?  If so, that seems fine with me if you're willing to do that.

**Comment by bbarker** [comment]
I don't think there's much metadata to add, my understanding is that the main thing is to try to fix issues if the package fails to build on a newer release of stackage (I wouldn't quite call it an obligation); full details are at https://github.com/commercialhaskell/stackage/blob/master/MAINTAINERS.md

Of course, if there is an issue, I'll raise it here and/or fix it if I can.

**Comment by bbarker** [comment]
Update: both UIO libraries are now on Stackage nightly (but not LTS yet): https://www.stackage.org/nightly-2020-06-08
