### ISSUE TITLE
OK to reproduce blogpost on UIO in markdown?

### ISSUE THREAD

**Issue by bbarker** [singpolyma/unexceptionalio#20]
Hi, I'm working on a wrapper that will hopefully emulate a few of the features of [ZIO](https://zio.dev/docs/overview/overview_index), but it relies heavily on UIO. Was wondering if I could back up your blog post: https://singpolyma.net/2018/05/error-handling-in-haskell/ in a markdown file.

Best,

**Comment by singpolyma** [comment]
Of course!  If it matters, license is: http://creativecommons.org/licenses/by/4.0/

**Comment by bbarker** [comment]
Thanks! I put it up at https://github.com/bbarker/haskell-zio/blob/master/docs/UIO.md
