### ISSUE TITLE
Polishing

### ISSUE THREAD

**Issue by nikita-volkov** [singpolyma/unexceptionalio#6]
Naming is an extremely sensitive issue for such a lightweight package, which has a potential of becoming a ubiquitous dependency. So far the reasons stopping me from adopting it are mostly tied to the controversial naming of the definitions. That being an issue itself also makes me conclude that the API is a highly likely subject to radical changes, which is another reason stopping me from adopting it. So, what I want to say is that, while the library has a great potential, it requires polishing to become useful.

---

I think we all agree that the current title of the package and of its fundamental type is less than optimal. It's neither descriptive, catchy, easy to remember or type. So, as a first order of business, I suggest to start looking for another name. Here are my candidates:

* "safe-io". Pros: short, easy to remember and type. Cons: a bit ambiguous meaning (not any more ambiguous, than "unexceptional" though).
* "exception-free-io". Pros: while "ExceptionFree" is as just many characters to type as "Unexceptional", it's also a clear definition. Cons: all the rest.

I'm inviting you to provide other candidates.

---

Since "IO" is itself an abbreviation, combining it with a complete word does not only produce more characters to type, but is even not very consistent. So, as the second order of business, whatever the title we come up with, I propose to only use it's abbreviated form in all the definitions inside the library. This implies getting rid of the type-alias redundancy, which itself represents a confusion burden on the API. 

IOW, depending on the title of the library, I suggest to only use an abbreviation (e.g., "UIO", "SIO", "EFIO"), and to explain its meaning in the docs.

---

IMO, some functions of the API also require a bit of reconsideration. But let's solve the above issues first.

---

Pinging @Gabriel439 to join the discussion.

**Comment by singpolyma** [comment]
I'm open to suggestions, but I really like the current name and think it is both pretty clear, and a nice playful use of english.

**Comment by singpolyma** [comment]
Also, I already provide an abbreviation-only type alias, at your request.

**Comment by Gabriel439** [comment]
Why not reverse the type and synonym: make `UIO` the name of the type and `UnexceptionalIO` the name of the type synonym?

**Comment by singpolyma** [comment]
I could reverse the names, I guess, if people want.  I'm pretty sure it's the same either way.

**Comment by Gabriel439** [comment]
The difference is which one will show up in error messages and inferred types.  I learned this the hard way with `pipes` (where `Proxy` shows up everywhere in error messages)

**Comment by singpolyma** [comment]
@Gabriel439 that's a fair point.  But wouldn't it make sense, then, to have the more expressive/explicit name show up in the type errors?

**Comment by nikita-volkov** [comment]
Part of my proposal is actually to get rid of `UnexceptionalIO` altogether, leaving only `UIO`. The reason is that it's highly unlikely that anyone will choose to use such a long name and that existence of alternative names for the same thing only breeds confusion.

**Comment by Gabriel439** [comment]
@singpolyma Imagine what Haskell would be like if `IO` were instead named `InputOutput`.  That's how some people feel about `UnexceptionalIO`.

**Comment by singpolyma** [comment]
Alright, if you both feel so strongly I will release a new major revision soon with with just `UIO` as the datatype name.

**Comment by ocharles** [comment]
I believe this is done now? Though I would also suggest the type class matches `mtl` naming and is `MonadUIO`.
